name: Deploy Xcorpion Landing to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Xcorpion Landing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build
          tar -czf frontend-dist.tar.gz dist

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Copy Frontend Build to VPS
        run: |
          scp -o StrictHostKeyChecking=no frontend-dist.tar.gz ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:/var/www/xcorpion-landing/

      - name: Deploy Frontend to VPS
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \ . "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \ . "$NVM_DIR/bash_completion"
            nvm use node || echo "NVM not found, skipping..."

            cd /var/www/xcorpion-landing
            git pull origin main

            rm -rf dist
            tar -xzf frontend-dist.tar.gz

            rm frontend-dist.tar.gz
          EOF

      - name: Restart Nginx
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo systemctl restart nginx
          EOF
